spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MYSQL
  jpa:
    hibernate:
      ddl-auto: create
custom:
  site:
    baseUrl: "http://localhost:8080"
  temp:
    dirPath: ${HOME}/Desktop/os/medium_test/temp
  genFile:
    dirPath: ${HOME}/Desktop/os/medium_test